# -*- coding: utf-8 -*-
"""exp10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdK6xGGi4T3_BDMHzFq-pVkqPzm2OMYd
"""



"""10)Write a python program to replace the missing values in the data by comparing with the neighboring data."""

import pandas as pd
# Read the CSV file
input_file = 'missing.xlsx'
output_file = 'missingfill.xlsx'
data = pd.read_excel(input_file)
# Iterate through each column
for col in data.columns:
    # Iterate through each row
    for i in range(len(data)):
        if pd.isna(data.at[i, col]):  # Check if the value is missing
            # Find the neighboring values
            prev_val = data.at[i - 1, col] if i > 0 else None
            next_val = data.at[i + 1, col] if i < len(data) - 1 else None

            # Calculate the mean of neighboring values
            if prev_val is None and next_val is None:
                mean = 0  # Default value if no neighbors are available
            elif prev_val is None:
                mean = next_val
            elif next_val is None:
                mean = prev_val
            else:
                mean = (prev_val + next_val) / 2

            # Replace the missing value with the calculated mean
            data.at[i, col] = mean

# Write the updated data to a new CSV file
data.to_excel(output_file, index=False)
print("Missing values replaced and saved to", output_file)

pwd