# -*- coding: utf-8 -*-
"""EXP12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLTfobH5hYgI72Jd5uNBlopsfYKgYPGd
"""



"""12Develop an application to analyze Twitter Data using Python tools"""



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob

# Load the CSV file into a pandas DataFrame
data = pd.read_csv('twitter_data_1000.csv')

# Display basic information about the dataset
print(data.info())

# Display the first few rows of the dataset
print(data.head())

# Visualize the distribution of tweet sources
plt.figure(figsize=(10, 6))
sns.countplot(data=data, y='tweet')
plt.title('Tweet Sources Distribution')
plt.xlabel('Count')
plt.ylabel('tweet')
plt.show()

# Perform sentiment analysis using TextBlob
def get_sentiment(text):
    analysis = TextBlob(text)
    if analysis.sentiment.polarity > 0:
        return 'Positive'
    elif analysis.sentiment.polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

data['sentiment'] = data['tweet'].apply(get_sentiment)

# Visualize sentiment distribution
plt.figure(figsize=(8, 6))
sns.countplot(data=data, x='sentiment')
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.show()
data.to_csv('sanalysis410.csv')