# -*- coding: utf-8 -*-
"""exp1ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dguf-YSTjrWsKmo3zhD2uMcawtu8FBLD
"""



"""a)write a program to create a list,manipulate and slices it b)create a new list and add elements to it from another list,also create a matrix from two lists c)create same a,b steps for tuple and dictionary"""

#list creation:-
list=['hi','hello']
list

l1=['welcome']
print(l1)

#empty list:-
list1=[]
list1

#printing list elements:-
l2=[10,'hi',20.66]
print(l2)
l2

#creating a list of strings and accessing using index:-
l5=['hi','all']
l5[1]

#accessing elements from multi dimensional list:-
l1=[['DS','ML'],['PY','OS']]
print(l1[0][1])
print(l1[1][0])

#lists negative indexing:-
l1=[1,'one',2,'two',3,'three']
print(l1[-1])
print(l1[-4])

#taking input of python list:-
string=input("enter elements(space-separated):")
list=string.split()
print('list is:',list)

#string input to integer conversion:-
n=int(input("enter size of list:"))
l1=list(map(int,input("enter integer").strip().split()))[:n]
print(l1)