# -*- coding: utf-8 -*-
"""exp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvavA5qaVNSh9AGt_v3ITvYSo11-lBoW

4)Consider the sample data Mean velocity: 0.2474, 0.1235, 0.1737, 0.1824

Standard deviation of velocity: 0.3314, 0.2278, 0.2836, 0.2645 i.

Write a Python program to create bar plots with error bars on the same figure.

Attach a text label above each bar displaying means.
"""

import matplotlib.pyplot as plt

# Sample data
mean_velocity = [0.2474, 0.1235, 0.1737, 0.1824]
std_velocity = [0.3314, 0.2278, 0.2836, 0.2645]
labels = ['Sample 1', 'Sample 2', 'Sample 3', 'Sample 4']

# Create bar plots with error bars and text labels
plt.bar(labels, mean_velocity, yerr=std_velocity, capsize=5, color='skyblue')

# Add text labels above each bar displaying means
for i in range(len(mean_velocity)):
    plt.text(i, mean_velocity[i] + 0.01, str(mean_velocity[i]), ha='center', va='bottom')

# Add labels and title
plt.xlabel('Sample')
plt.ylabel('Mean Velocity')
plt.title('Mean Velocity with Error Bars')

# Show the plot
plt.tight_layout()
plt.show()