# -*- coding: utf-8 -*-
"""exp6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBspX4TbaBjkua7fHedRF6Ld-VGAcMJV
"""





"""6.Develop an application to analyze Stock Market Data using Python tools"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

def get_stock_data(ticker, start_date, end_date):
    stock_data = yf.download(ticker, start=start_date, end=end_date)
    return stock_data

def plot_stock_data(stock_data, ticker):
    plt.figure(figsize=(12, 6))
    plt.plot(stock_data['Close'], label=f"{ticker} Close Price")
    plt.title(f"{ticker} Stock Price")
    plt.xlabel("Date")
    plt.ylabel("Price (USD)")
    plt.legend()
    plt.grid()
    plt.show()

def analyze_stock_data(stock_data):
    # Add your analysis code here (e.g., calculate moving averages, daily returns, etc.)

    # Example: Calculate and plot 50-day moving average
    stock_data['MA_50'] = stock_data['Close'].rolling(window=50).mean()
    plt.figure(figsize=(12, 6))
    plt.plot(stock_data['Close'], label="Close Price")
    plt.plot(stock_data['MA_50'], label="50-day Moving Average")
    plt.title("Stock Price with 50-day Moving Average")
    plt.xlabel("Date")
    plt.ylabel("Price (USD)")
    plt.legend()
    plt.grid()
    plt.show()

def main():
    # Enter the stock ticker symbol, start date, and end date for the analysis
    ticker = 'AAPL'  # Example: Apple Inc.
    start_date = '2022-01-01'
    end_date = '2022-06-30'

    stock_data = get_stock_data(ticker, start_date, end_date)
    if stock_data.empty:
        print(f"No data available for {ticker} between {start_date} and {end_date}.")
        return

    # Display basic information about the stock data
    print(stock_data.head(20))
    print(stock_data.info())

    # Plot stock price data
    plot_stock_data(stock_data, ticker)

    # Analyze stock data
    analyze_stock_data(stock_data)

if __name__ == "__main__":
    main()