# -*- coding: utf-8 -*-
"""exp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYnYKG8ZghQ0rVmHRm41kgo0VgdjQDs4
"""

pwd

from google.colab import drive
drive.mount('/content/drive')



"""7)Given the iris dataset: https://archive.ics.uci.edu/ml/datasets/iris
1. How many rows does it contain? How many columns?
2. Compute the average petal length
3. Compute the average of all numerical columns


"""

import pandas as pd

# Load the dataset into a DataFrame
df = pd.read_csv("iris data final.csv",index_col=0)
print(df)

# Get the number of rows and columns
num_rows = df.shape[0]
num_columns = df.shape[1]

print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

# Calculate the average petal length

average_petal_length = df['petal length'].mean()

print("Average petal length:", average_petal_length)

# Calculate the average of all numerical columns
averages = df.mean(numeric_only=True)

print("Averages of numerical columns:")
print(averages)