# -*- coding: utf-8 -*-
"""exp8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYfadLmr0-Wmc9H51EmJ5o8bBsk3YeiI
"""



"""8)1.Extract the petal length outliers (i.e. those rows whose petal length is 50% longer aggregate () group by (), than the average petal length)
2.Compute the standard deviation of all columns, for each iris species.
3.Extract the petal length outliers (as above) for each iris species
"""

import pandas as pd

# Step 1: Read the data and extract the petal length outliers for the entire dataset
data = pd.read_csv("iris data.csv",index_col=0)

# Calculate the average petal length for the entire dataset
average_petal_length = data['petal length'].mean()

# Calculate the threshold for outliers (50% longer than the average petal length)
threshold = 1.5 * average_petal_length

# Extract petal length outliers for the entire dataset
petal_length_outliers = data[data['petal length'] > threshold]

# Step 2: Compute the standard deviation of all columns for each iris species
std_dev_by_species = data.groupby('variety').std()

# Step 3: Extract the petal length outliers for each iris species
petal_length_outliers_by_species = data.groupby('variety').apply(lambda group: group[group['petal length'] > (1.25 * group['petal length'].mean())])

# Print the results
print("Petal Length Outliers for the entire dataset:")
print(petal_length_outliers)

print("\nStandard Deviation of all columns for each iris species:")
print(std_dev_by_species)

print("\nPetal Length Outliers for each iris species:")
print(petal_length_outliers_by_species)